### ISSUE TITLE
Problems with params_proto

### ISSUE THREAD

**Issue by percypeng5221** [pmanoonpong/MITrapidmotoradaptation#1]
From the code you guys were importing params_proto like this:
`from params_proto.neo_proto import Meta`
but right now it seems that we don't have neo_proto from the package params_proto.
I changed to
`from params_proto.proto import Meta`
and all the subpackages like Meta still exsist.
However, I got this error:
```
Importing module 'gym_38' (/home/percyp/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/percyp/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 2.0.1
Device count 1
/home/percyp/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/percyp/.cache/torch_extensions/py38_cu118 as PyTorch extensions root...
Emitting ninja build file /home/percyp/.cache/torch_extensions/py38_cu118/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Traceback (most recent call last):
  File "scripts/test.py", line 51, in <module>
    run_env(render=True, headless=True)
  File "scripts/test.py", line 32, in run_env
    env = VelocityTrackingEasyEnv(sim_device='cuda:0', headless=False, cfg=Cfg)
  File "/home/percyp/code/MITrapidmotoradaptation/mini_gym/envs/mini_cheetah/velocity_tracking/velocity_tracking_easy_env.py", line 38, in __init__
    gymutil.parse_sim_config(vars(cfg.sim), sim_params)
  File "/home/percyp/isaacgym/python/isaacgym/gymutil.py", line 407, in parse_sim_config
    parse_physx_config(sim_cfg["physx"], sim_options)
  File "/home/percyp/isaacgym/python/isaacgym/gymutil.py", line 438, in parse_physx_config
    parse_float_int_bool(physx_cfg, sim_options.physx, params)
  File "/home/percyp/isaacgym/python/isaacgym/gymutil.py", line 448, in parse_float_int_bool
    if opt in cfg:
TypeError: argument of type 'Meta' is not iterable
```
Can you help me figure it out?

**Comment by percypeng5221** [comment]
If you check their document: [https://github.com/geyang/params-proto/blob/master/README.md](url), you can see that they move neo_proto to the top.
